from django.urls import path
from . import views
urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('profildata/', views.profil_data, name="profildata"),
    path('addfeature/', views.addFeatures_one, name="addfeature"),
    path('addpost/', views.addpost, name="addpost"),
    path('getposts/', views.getposts, name="getposts"),
    path('editname/', views.editNameD, name="editname"),
    path('editusername/', views.editUserNameD, name="editusername"),
    path('editpio/', views.editPioD, name="editpio"),
    path('editemail/', views.editEmailD, name="editemail"),
    path('editpassword/', views.editPasswordD, name="editpassword"),
    path('editprofilimage/', views.editProfilImageD, name="editprofilimage"),
    path('addcomment/',views.addcommentD, name="addcomment"),
    path('getcomments/', views.getCommentsD, name="getcomments"),
    path('addlike/', views.addLikeD, name="addlike"),
    path('deletepost/', views.deletePostF, name="deletepost"),
    path('editpost/', views.editPostF, name="editpost"),
    path('savepost/', views.savePostF, name="savepost"),
    path('getsavedposts/', views.getSavedPostsF, name="getsavedposts"),
    path('getsharedpostdata/', views.getSharedPostsF, name="getsharedpostdata"),
    path('sharepost/', views.sharePostF, name="sharepost"),
    path('search/', views.SearchF, name="search"),
    path('deletecomment/', views.DeleteCommentF, name="deletecomment"),
    path('getfollowingemails/', views.getFollowingEmailsF, name="getfollowingemails"),
    path("follow/", views.FollowF, name="follow"),
    path('getpost/', views.getPost, name="getpost"),
    path('getfollowers/', views.getFollowersF, name="getfollowers"),
    path('getfollowing/', views.getFollowingF, name="getfollowing"),
    path('getmaindata/', views.getMainDataF, name="getmaindata"),
    path('getrooms/', views.getRooms, name="getrooms"),
    path('seenmessages/', views.seenMessagesF, name="seenmessages"),
    path('updatestate/', views.updateStateF, name="updatestate"),
    path('deletechat/', views.deleteChatF, name="deletechat")
]